# /// script
# requires-python = ">=3.8"
# ///

from .admin import (
    Billing,
    Challenges,
    Devices as AdminDevices,
    Firmware,
    Groups,
    Locations as AdminLocations,
    Narratives,
    Organizations,
    Reports,
    System,
    Tags as AdminTags,
    UserGroups,
    Users,
)
from .api import API
from .app import (
    AI,
    AppFiles,
    Authentication,
    CloudConnectivity,
    CloudsIntegration,
    Community,
    DeviceFiles,
    DeviceMeasurements,
    Devices,
    DeviceTypesAndParameters,
    EnergyManagement,
    Locations,
    PaidServices,
    ProfessionalMonitoring,
    RAG,
    Rules,
    SystemAndUserProperties,
    UserAccounts,
    UserCommunication,
    Weather,
    Websocket,
)
from .bot import (
    Analytic,
    BotDeveloper,
    BotStore,
    DeveloperTeams,
    Execution,
)

__all__ = [
    "API",
    # App APIs
    "AI",
    "AppFiles",
    "Authentication",
    "CloudConnectivity",
    "CloudsIntegration",
    "Community",
    "DeviceFiles",
    "DeviceMeasurements",
    "Devices",
    "DeviceTypesAndParameters",
    "EnergyManagement",
    "Locations",
    "PaidServices",
    "ProfessionalMonitoring",
    "RAG",
    "Rules",
    "SystemAndUserProperties",
    "UserAccounts",
    "UserCommunication",
    "Weather",
    "Websocket",
    # Admin APIs
    "AdminDevices",
    "AdminLocations",
    "AdminTags",
    "Billing",
    "Challenges",
    "Firmware",
    "Groups",
    "Narratives",
    "Organizations",
    "Reports",
    "System",
    "UserGroups",
    "Users",
    # Bot APIs
    "Analytic",
    "BotDeveloper",
    "BotStore",
    "DeveloperTeams",
    "Execution",
]
