# /// script
# requires-python = ">=3.8"
# dependencies = [
#   "requests",
# ]
# ///

import json
from typing import Dict

from .api import API


class Services(API):
    def get_bot_key(self, app_instance_id: int):
        params = {"app_instance_id": app_instance_id}
        result = self.adapter.get(
            "/espapi/analytic/appkey", ep_headers=params
        )
        return result


    def location_scenes_history(): ...
    def get_parameters(): ...
    def send_commands(): ...
    def inject_parameters(): ...
    def send_a_notification(): ...
    def send_location_notification(): ...
    def post_zendesk_ticket(): ...
    def send_message(): ...

    def update_messages(
            self,
            messages: Dict,
    ):
        return self.adapter.put(
            "/espapi/cloud/json/messages",
            ep_json=json.dumps(messages),
        )
    def send_mms(): ...
    def get_call_center(): ...
    def update_call_center(): ...
    def get_call_center_alerts(): ...
    def test_execution(): ...
    def execute_again(): ...
    def get_challenge_participants(): ...
    def start_execution(): ...
    def submit_data_request(): ...
    def send_fall_event_feedback(): ...


class Questions(API):
    def ask_question(): ...
    def delete_question(): ...
    def update_response(): ...
    def get_responses(): ...
    def define_question_collection(): ...
    def get_question_collections(): ...
    def clear_question_collection(): ...


class Tags(API):
    def apply_tags(): ...
    def delete_tag(): ...
    def get_tags(): ...


class Variables(API):
    def load_variable(): ...
    def save_variable(): ...
    def delete_variable(): ...


class VoiceCalls(API):
    def make_voice_call(): ...
    def set_answer_voice_call(): ...
    def delete_answer_voice_call(): ...


class AI(API):
    def call_ai(): ...
