# /// script
# requires-python = ">=3.8"
# ///

from .apis import (
    AdminDevices,
    AdminLocations,
    AdminTags,
    AI,
    API,
    AppFiles,
    Authentication,
    Billing,
    BotDeveloper,
    BotStore,
    Challenges,
    CloudConnectivity,
    CloudsIntegration,
    Community,
    DeveloperTeams,
    DeviceFiles,
    DeviceMeasurements,
    Devices,
    DeviceTypesAndParameters,
    EnergyManagement,
    Execution,
    Groups,
    Locations,
    Narratives,
    Organizations,
    PaidServices,
    ProfessionalMonitoring,
    Questions,
    RAG,
    Rules,
    Services,
    System,
    SystemAndUserProperties,
    Tags,
    UserAccounts,
    UserCommunication,
    UserGroups,
    Users,
    Variables,
    VoiceCalls,
    Weather,
    Websocket,
)
from .caredaily import CareDaily
from .exceptions import CareDailyException
from .models import (
    APIKeyType,
    Cloud,
    MQTT,
    PythonRuntime,
    Result,
    ResultCode,
    Server,
    ServerType,
    TimeZone,
)

__all__ = [
    "APIKeyType",
    "CareDaily",
    "CareDailyException",
    "Cloud",
    "MQTT",
    "PythonRuntime",
    "Result",
    "ResultCode",
    "Server",
    "ServerType",
    "TimeZone",
    # Apis
    "API",
    # App APIs
    "CloudConnectivity",
    "Authentication",
    "UserAccounts",
    "Locations",
    "Devices",
    "DeviceMeasurements",
    "UserCommunication",
    "SystemAndUserProperties",
    "DeviceFiles",
    "AppFiles",
    "Rules",
    "PaidServices",
    "ProfessionalMonitoring",
    "EnergyManagement",
    "Weather",
    "DeviceTypesAndParameters",
    "CloudsIntegration",
    "RAG",
    "Community",
    "Websocket",
    # Admin APIs
    "System",
    "Organizations",
    "Groups",
    "Users",
    "UserGroups",
    "AdminDevices",
    "AdminLocations",
    "Challenges",
    "AdminTags",
    "Narratives",
    "Billing",
    # Bot APIs
    "BotDeveloper",
    "DeveloperTeams",
    "BotStore",
    # Service APIs
    "Services",
    "Questions",
    "Tags",
    "Variables",
    "VoiceCalls",
    "AI",
    # Device APIs
    "Execution",
]
